### ISSUE TITLE
[pip v1.1] pip install with requirements file fails; version 0.0.0 conflicts with numexpr==2.4

### ISSUE THREAD

**Issue by alex-dr** [pydata/numexpr#154]
This doesn't affect newer versions of pip (tested 1.5.6), which merely print a warning:
```Requested numexpr==2.4 (from -r reqs.txt (line 1)), but installing version 0.0.0```

But with pip 1.1:
```
$ echo "numexpr==2.4" > reqs.txt
$ pip install -r reqs.txt 
Downloading/unpacking numexpr==2.4 (from -r reqs.txt (line 1))
  Downloading numexpr-2.4.tar.gz (84Kb): 84Kb downloaded
  Running setup.py egg_info for package numexpr
    
    warning: no previously-included files found matching 'numexpr/__config__.py'
    warning: no previously-included files found matching 'RELEASING.txt'
  Source in /path-to-virtualenv/build/numexpr has the version 0.0.0, which does not match the requirement numexpr==2.4 (from -r reqs.txt (line 1))
Source in /path-to-virtualenv/build/numexpr has version 0.0.0 that conflicts with numexpr==2.4 (from -r reqs.txt (line 1))
Storing complete log in /home/$USER/.pip/pip.log
```

Regular ```$ pip install numexpr==2.4``` works with a warning that 0.0.0 is being installed instead.

And, full .pip/pip.log:
```
------------------------------------------------------------
/path-to-virtualenv/bin/pip run on Mon Oct 20 19:28:46 2014
Downloading/unpacking numexpr==2.4 (from -r reqs.txt (line 1))

[... URL search omitted ...]
  Downloading from URL https://pypi.python.org/packages/source/n/numexpr/numexpr-2.4.tar.gz#md5=df7e8d9e9dbb145b56d43c465c2bf854 (from https://pypi.python.org/simple/numexpr/)
  Running setup.py egg_info for package numexpr

    running egg_info
    creating pip-egg-info/UNKNOWN.egg-info
    writing requirements to pip-egg-info/UNKNOWN.egg-info/requires.txt
    writing pip-egg-info/UNKNOWN.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/UNKNOWN.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/UNKNOWN.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/UNKNOWN.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/UNKNOWN.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'numexpr/__config__.py'

    warning: no previously-included files found matching 'RELEASING.txt'

    writing manifest file 'pip-egg-info/UNKNOWN.egg-info/SOURCES.txt'
  Source in /path-to-virtualenv/build/numexpr has the version 0.0.0, which does not match the requirement numexpr==2.4 (from -r reqs.txt (line 1))

Source in /path-to-virtualenv/build/numexpr has version 0.0.0 that conflicts with numexpr==2.4 (from -r reqs.txt (line 1))

Exception information:
Traceback (most recent call last):
  File "/path-to-virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/path-to-virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/path-to-virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1014, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/path-to-virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 366, in assert_source_matches_version
    % (display_path(self.source_dir), version, self))
InstallationError: Source in /path-to-virtualenv/build/numexpr has version 0.0.0 that conflicts with numexpr==2.4 (from -r reqs.txt (line 1))
'''
```

**Comment by FrancescAlted** [comment]
I would also say that this is an issue with pip.  Will close, but feel free to re-open if appropriate.

**Comment by blootsvoets** [comment]
With `pip` 6.1.1 the same problem occurs:
```
Requested numexpr==2.4.1 (from -r requirements.txt (line 2)), but installing version None
```
Subsequent installs from requirements.txt fail because they require `numexpr>=2.0.0`. This is especially annoying when using Travis CI, because then the automatic build fails.

Could the version number explicitly be set in the `metadata` dict in setup.py, either directly or calling `version.py`?

**Comment by blootsvoets** [comment]
I'm sorry, the message threw me off, but actually another package was to blame for not installing correctly. It would still be nice to have the message fixed though.

**Comment by FrancescAlted** [comment]
Do you think f3eac6a would work?

**Comment by bastianl** [comment]
I am having the same problem when trying to install numexpr and numpy in the same requirements.txt file

**Comment by jackchua-placed** [comment]
upgrading pip using

`pip install --upgrade pip`

seems to do the trick, though it does result in a warning.

**Comment by jackchua** [comment]
upgrading pip using

`pip install --upgrade pip`

seems to do the trick, though it does result in a warning.

**Comment by ransage** [comment]
Thanks @jackchua - that does the trick.  I just updated our install procedure to upgrade every time we install and now it's working across hosts:

        $(VENV_BIN_DIR)/pip install --upgrade pip
        $(VENV_BIN_DIR)/pip install -q --no-deps -r requirements.txt

Note that the --no-deps is not very helpful for development, but conforms to the pip recommendations for [pinning versions]( https://pip.pypa.io/en/stable/user_guide/#pinned-version-numbers)

**Comment by FrancescAlted** [comment]
Ok.  Thanks for the additional checks.  Closing again.
