### ISSUE TITLE
Installing and compilation throwing error with msvccompiler "AttributeError: 'MSVCCompiler' object has no attribute 'compiler_cxx'"

### ISSUE THREAD

**Issue by nick-schultz** [pydata/numexpr#191]
I am seeing the following error when trying to use pip to install numexpr. Please let me know if there is anything I can supply to help solve this bug.  

Thanks!
Nick

Using python 3.4-x64, my current virtualenv has.

```
beautifulsoup4==4.4.1
numpy==1.10.1
pandas==0.17.0
pypyodbc==1.3.3
python-dateutil==2.4.2
pytz==2015.7
six==1.10.0
SQLAlchemy==1.0.9
```

The main error I am getting is:

```
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_cxx'
```

Output 

```
Installing 'numexpr==2.4'
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting numexpr==2.4
  Downloading numexpr-2.4.tar.gz (84kB)
  Requested numexpr==2.4, but installing version None
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6 in c:\python\python34\lib\site-packages (from numexpr==2.4)
Installing collected packages: numexpr
  Running setup.py install for numexpr
    Appending numexpr.tests configuration to numexpr
    Ignoring attempt to set 'name' (from 'numexpr' to 'numexpr.tests')
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    build_src
    building py_modules sources
    building extension "numexpr.interpreter" sources
    build_src: building npy-pkg config files
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    customize MSVCCompiler
    Warning: Assuming default configuration (numexpr\tests/{setup_tests,setup}.py was not found)Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nschultz\AppData\Local\Temp\pip-build-bpuupd3j\numexpr\setup.py", line 219, in <module>
        setup_package()
      File "C:\Users\nschultz\AppData\Local\Temp\pip-build-bpuupd3j\numexpr\setup.py", line 215, in setup_package
        setup(**metadata)
      File "C:\python\Python34\lib\site-packages\numpy\distutils\core.py", line 169, in setup
        return old_setup(**new_attr)
      File "C:\python\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\python\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\python\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\install.py", line 62, in run
        r = self.setuptools_run()
      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "C:\python\Python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\python\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\python\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\build.py", line 47, in run
        old_build.run(self)
      File "C:\python\Python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\python\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\python\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\build_ext.py", line 203, in run
        compiler.customize(self.distribution, need_cxx=need_cxx_compiler)
      File "C:\python\Python34\lib\site-packages\numpy\distutils\ccompiler.py", line 28, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
      File "C:\python\Python34\lib\site-packages\numpy\distutils\ccompiler.py", line 388, in CCompiler_customize
        elif not self.compiler_cxx:
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler_cxx'
    Complete output from command C:\python\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\nschultz\\AppData\\Local\\Temp\\pip-build-bpuupd3j\\numexpr\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\nschultz\AppData\Local\Temp\pip-wryeq6wm-record\install-record.txt --single-version-externally-managed --compile:
    Appending numexpr.tests configuration to numexpr

    Ignoring attempt to set 'name' (from 'numexpr' to 'numexpr.tests')

    running install

    running build

    running config_cc

    unifing config_cc, config, build_clib, build_ext, build commands --compiler options

    running config_fc

    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options

    running build_src

    build_src

    building py_modules sources

    creating build

    creating build\src.win-amd64-3.4

    creating build\src.win-amd64-3.4\numexpr

    building extension "numexpr.interpreter" sources

    build_src: building npy-pkg config files

    running build_py

    creating build\lib.win-amd64-3.4

    creating build\lib.win-amd64-3.4\numexpr

    copying numexpr\cpuinfo.py -> build\lib.win-amd64-3.4\numexpr

    copying numexpr\expressions.py -> build\lib.win-amd64-3.4\numexpr

    copying numexpr\necompiler.py -> build\lib.win-amd64-3.4\numexpr

    copying numexpr\utils.py -> build\lib.win-amd64-3.4\numexpr

    copying numexpr\version.py -> build\lib.win-amd64-3.4\numexpr

    copying numexpr\__init__.py -> build\lib.win-amd64-3.4\numexpr

    copying build\src.win-amd64-3.4\numexpr\__config__.py -> build\lib.win-amd64-3.4\numexpr

    creating build\lib.win-amd64-3.4\numexpr\tests

    copying .\numexpr\tests\test_numexpr.py -> build\lib.win-amd64-3.4\numexpr\tests

    copying .\numexpr\tests\__init__.py -> build\lib.win-amd64-3.4\numexpr\tests

    Skipping implicit fixer: buffer

    Skipping implicit fixer: idioms

    Skipping implicit fixer: set_literal

    Skipping implicit fixer: ws_comma

    running build_ext

    customize MSVCCompiler

    customize MSVCCompiler using build_ext

    customize MSVCCompiler

    Warning: Assuming default configuration (numexpr\tests/{setup_tests,setup}.py was not found)Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\nschultz\AppData\Local\Temp\pip-build-bpuupd3j\numexpr\setup.py", line 219, in <module>

        setup_package()

      File "C:\Users\nschultz\AppData\Local\Temp\pip-build-bpuupd3j\numexpr\setup.py", line 215, in setup_package

        setup(**metadata)

      File "C:\python\Python34\lib\site-packages\numpy\distutils\core.py", line 169, in setup

        return old_setup(**new_attr)

      File "C:\python\Python34\lib\distutils\core.py", line 148, in setup

        dist.run_commands()

      File "C:\python\Python34\lib\distutils\dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "C:\python\Python34\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\install.py", line 62, in run

        r = self.setuptools_run()

      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\install.py", line 36, in setuptools_run

        return distutils_install.run(self)

      File "C:\python\Python34\lib\distutils\command\install.py", line 539, in run

        self.run_command('build')

      File "C:\python\Python34\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\python\Python34\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\build.py", line 47, in run

        old_build.run(self)

      File "C:\python\Python34\lib\distutils\command\build.py", line 126, in run

        self.run_command(cmd_name)

      File "C:\python\Python34\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\python\Python34\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\python\Python34\lib\site-packages\numpy\distutils\command\build_ext.py", line 203, in run

        compiler.customize(self.distribution, need_cxx=need_cxx_compiler)

      File "C:\python\Python34\lib\site-packages\numpy\distutils\ccompiler.py", line 28, in <lambda>

        m = lambda self, *args, **kw: func(self, *args, **kw)

      File "C:\python\Python34\lib\site-packages\numpy\distutils\ccompiler.py", line 388, in CCompiler_customize

        elif not self.compiler_cxx:

    AttributeError: 'MSVCCompiler' object has no attribute 'compiler_cxx'

    ----------------------------------------
    Command "C:\python\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\nschultz\\AppData\\Local\\Temp\\pip-build-bpuupd3j\\numexpr\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\nschultz\AppData\Local\Temp\pip-wryeq6wm-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\nschultz\AppData\Local\Temp\pip-build-bpuupd3j\numexpr
'numexpr==2.4' failed to install. Exit code: 1
```

**Comment by Gustavosdo** [comment]
+1

I have the same problem.
I'm using Python 3.4. Windows x86...

**Comment by fimion** [comment]
+1

I have the same issue with Python 3.5 on windows x86

**Comment by suokunlong** [comment]
+1

Same issue with python versoin 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)].
I already have Visual Studio 2015 installed and have already sucessfully build numpy, but building numexpr fails.

**Comment by FrancescAlted** [comment]
Hmm, I am not a Windows savvy guy.  Anyone here wants to provide a fix for this one?

**Comment by robbmcleod** [comment]
Everyone, this generally means you don't have the right MS compiler.  It could also happen if you don't open the system prompt with the right environment variables set.  Generally every MSVC compiler also comes with an icon that sets all the environment variables for itself.  For Python 2.7, to compile numexpr, I generally had to use Visual Studio 2008 Pro.  The MS compiler for Python didn't cut it. One could try various SDKs as well.

**Comment by robbmcleod** [comment]
I do believe this was fixed with the addition of `distutils._msvccompiler`.

**Comment by ChenJiaDong9219** [comment]
@robbmcleod added where?

**Comment by robbmcleod** [comment]
I'm not sure exactly what I meant there; I should have been more clear in my language.  I vaguely remember there was a change in `distutils` itself that fixed this.

https://github.com/python/cpython/commits/master/Lib/distutils/_msvccompiler.py

Perhaps this one:

https://github.com/python/cpython/commit/31202eaa5c735044d9007f448b7f41b2c00f5f69#diff-d962ba8e352edf080a341706a50c13b0
