### ISSUE TITLE
ValueError: Integers to negative integer powers are not allowed

### ISSUE THREAD

**Issue by ghisvail** [pydata/numexpr#239]
Forwarding a bug [1] occurring in Debian with the current `numexpr` package. The full build log is available here [2]. A copy of the relevant portion of the build log containing the error is pasted below for convenience.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848771
[2] http://aws-logs.debian.net/2016/12/19/numexpr_2.6.1-2_unstable.log

Error log:
```
======================================================================
ERROR: test_scalar0_int_aggressive_OPERATIONS_0313 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_int_aggressive_POW_TESTS_0368 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_int_moderate_OPERATIONS_0187 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_int_moderate_POW_TESTS_0242 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_int_none_OPERATIONS_0061 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_int_none_POW_TESTS_0116 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_long_aggressive_OPERATIONS_0691 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_long_aggressive_POW_TESTS_0746 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_long_moderate_OPERATIONS_0565 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_long_moderate_POW_TESTS_0620 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_long_none_OPERATIONS_0439 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar0_long_none_POW_TESTS_0494 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar1_int_aggressive_POW_TESTS_2156 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar1_int_moderate_POW_TESTS_2031 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar1_int_none_POW_TESTS_1906 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar1_long_aggressive_POW_TESTS_2531 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar1_long_moderate_POW_TESTS_2406 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar1_long_none_POW_TESTS_2281 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar2_int_aggressive_POW_TESTS_3941 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar2_int_moderate_POW_TESTS_3816 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar2_int_none_POW_TESTS_3691 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar2_long_aggressive_POW_TESTS_4316 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar2_long_moderate_POW_TESTS_4191 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

======================================================================
ERROR: test_scalar2_long_none_POW_TESTS_4066 (__main__.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 1011, in method
    return func()
  File "numexpr/tests/test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.

----------------------------------------------------------------------
Ran 5441 tests in 5.616s

FAILED (errors=24)
```

**Comment by avalentino** [comment]
@ghisvail , @FrancescAlted it seems to be related to a backward incompatible change in numpy 1.12 [1]
Now

```python
a = np.array([1,2,3])
eval('(a+1)**-7')
```

raises the following error:

```
ValueError: Integers to negative integer powers are not allowed.
```

Please note that the above code only uses numpy.

It is not clear to me how to fix this issue, should we just drop offending tests?

[1] https://github.com/numpy/numpy/releases/tag/v1.12.0rc1

**Comment by FrancescAlted** [comment]
Yep, I remember some discussion going on on this subject on the numpy list.  A quick 'fix' for this would be to remove the offending tests, but if we want to keep numpy compatibility we should raise the same error than numpy too.

**Comment by avalentino** [comment]
@FrancescAlted a solution like the one implemented in #240 could make sense for you?

**Comment by FrancescAlted** [comment]
It makes total sense.  Many thanks Antonio!  I should try to find some time to do a new release soon!

**Comment by avalentino** [comment]
Thanks @FrancescAlted
