### ISSUE TITLE
Test failures with numpy 1.12

### ISSUE THREAD

**Issue by matthew-brett** [pydata/numexpr#244]
I believe numpy 1.12 introduced an error for negative powers of integers:

```
In [1]: import numpy as np
In [2]: np.__version__
Out[2]: '1.12.0'
In [3]: np.arange(2) ** -1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-92d721bbde3b> in <module>()
----> 1 np.arange(2) ** -1

ValueError: Integers to negative integer powers are not allowed.
```

This seems to cause a set of test failures in numexpr, of form:

```
======================================================================
ERROR: test_expressions((a+1) ** -1, test_scalar=0, dtype='int', optimization='none', exact=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27\lib\site-packages\numexpr\tests\test_numexpr.py", line 572, in method
    npval = eval(expr, globals(), this_locals)
  File "<string>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed
```

See: https://ci.appveyor.com/project/matthew-brett/numexpr-wheels/build/1.0.10/job/a3sykvp3sq7w8dyg#L133

**Comment by robbmcleod** [comment]
This was already handled in #240 I believe.
