### ISSUE TITLE
NE3: Pickling of C-NumExpr object

### ISSUE THREAD

**Issue by robbmcleod** [pydata/numexpr#258]
Currently the C-NumExpr object cannot be pickled.  Pickling of the C-NumExpr object would permit serialization of the module.  This could be valuable in two cases: 1.) Pickling of the wisdom (formally cache) dictionary, which stores all the compiled programs.  This could speed loading of pre-optimized Python code by a wisdom bank functionality similar to that seen in FFTW.  2.) Serialization within the context of parallel processes, as within the `multiprocessing` module or similar.  This could potentially allow for parallel processing libraries (`dask`, etc.) to use NE3 in a hybrid multi-processing/multi-threading environment, similar to the way OpenMPI hybrid mode permits the same.  Thus NE3 could leverage the RAM conservation and memory sharing of threads, while multiple processes are spawned in distributed/cluster environments.

The main issue as I see it is how to accommodate the constants.  These are the only components outside of `NumExprProgram` and `NumExprRegister` that are created in `NumExpr_init`, as the temporaries are initialized in the interpreter itself.  Practically we should investigate if the constant arrays really need to be BLOCK_SIZE in shape.  I suspect if a singleton array is broadcast with a multi-dimensional NumPy array, that a stride of zero is returned. In Python an empty tuple is returned; it remains to be seen what the C-API returns.  In this case, the BLOCK_SIZE shaped const is really a waste of L1 cache space.

**Comment by robbmcleod** [comment]
The most basic case for pickling was done in a7294613dcd0ebdbe2dd010caf5a7ebf8ab861e4.  Additional testing is required, and coverage in the `tests` submodule.

**Comment by robbmcleod** [comment]
Has been tested with `concurrent.futures`, seems to work.  Eventually I'd like to have an example script working with `dask`.

**Comment by Dan-Yeh** [comment]
Hi, is numexpr currently supporting multiprocessing module?

I'm running into pickling issue when I use dask and processed scheduler.
minimal repeatable code:
```python
import dask.array as da
import numexpr as ne

expr="exp((- 1 / 2) * D)"
numexpr_obj = ne.NumExpr(expr)
kernel_matrix = da.map_blocks(
    numexpr_obj.run,
    data,
    dtype=float,
)
kernel_matrix.compute(scheduler='processes')
```

and the output is:
```
Traceback (most recent call last):
  File "/Users/yehchenchen/Thesis/datafold-experiments/roseland_profiling/numexpr_prof.py", line 49, in <module>
    precompile(data)
  File "/Users/yehchenchen/Thesis/datafold-experiments/roseland_profiling/numexpr_prof.py", line 15, in precompile
    kernel_matrix.compute(scheduler='processes')
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/dask/base.py", line 314, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/dask/multiprocessing.py", line 233, in get
    result = get_async(
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/dask/local.py", line 499, in get_async
    fire_tasks(chunksize)
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/dask/local.py", line 481, in fire_tasks
    dumps((dsk[key], data)),
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/yehchenchen/Thesis/datafold-experiments/venv/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'numexpr.NumExpr' object
```

**Comment by robbmcleod** [comment]
Hi this issue is for Numexpr 3.x which is in an alpha state and isn't under active development anymore. I could look at what was done there to see if that feature could be back-ported.
