### ISSUE TITLE
AttributeError: 'module' object has no attribute 'machine' After import numexpr

### ISSUE THREAD

**Issue by dearhoper** [pydata/numexpr#269]
The system information: Python 2.7.6, cuda8.0, tensorflow-gpu-1.0.1, tflearn-0.3, numpy 1.12.1.
```
>>> import  numexpr as ne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numexpr-2.6.2-py2.7-linux-x86_64.egg/numexpr/__init__.py", line 42, in <module>
    from numexpr.tests import test, print_versions
  File "/usr/local/lib/python2.7/dist-packages/numexpr-2.6.2-py2.7-linux-x86_64.egg/numexpr/tests/__init__.py", line 11, in <module>
    from numexpr.tests.test_numexpr import test, print_versions
  File "/usr/local/lib/python2.7/dist-packages/numexpr-2.6.2-py2.7-linux-x86_64.egg/numexpr/tests/test_numexpr.py", line 299, in <module>
    class test_evaluate(TestCase):
  File "/usr/local/lib/python2.7/dist-packages/numexpr-2.6.2-py2.7-linux-x86_64.egg/numexpr/tests/test_numexpr.py", line 456, in test_evaluate
    if 'sparc' not in platform.machine():
AttributeError: 'module' object has no attribute 'machine'
```
What's the problem? Who can help me?

**Comment by robbmcleod** [comment]
Please cut and paste `numexpr.print_versions()` as a start -- well actually you probably can't do that...  For some reason the `platform` module on your architecture does not have a function called `machine()`.  This should not be possible, as the standard library defines it.

https://docs.python.org/2/library/platform.html

So you have some special Python install?

**Comment by dearhoper** [comment]
Python3.4 was previously installed.
Are they related?

**Comment by robbmcleod** [comment]
Can you run:

`import platform`
`platform.machine()`

?

**Comment by dearhoper** [comment]
The running information:
```Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'machine'```

**Comment by dearhoper** [comment]
Oh, my god, did I install a "fake" platform? 
Should I reinstall the python 2.7?

**Comment by dearhoper** [comment]
I searched all folders named 'platform':
```root@gpu01-ThinkStation-P700:~# find / -name platform -type d
/root/NVIDIA_CUDA-8.0_Samples/6_Advanced/interval/boost/config/platform
/lib/modules/3.13.0-106-generic/kernel/drivers/media/platform
/lib/modules/3.13.0-106-generic/kernel/drivers/platform
/lib/modules/3.19.0-25-generic/kernel/drivers/media/platform
/lib/modules/3.19.0-25-generic/kernel/drivers/platform
/sys/bus/platform
/sys/devices/platform
/usr/src/linux-headers-3.19.0-25-generic/include/config/genwqe/platform
/usr/src/linux-headers-3.19.0-25-generic/include/config/v4l/platform
/usr/src/linux-headers-3.19.0-25-generic/include/config/x86/platform
/usr/src/linux-headers-3.19.0-25-generic/include/config/wilink/platform
/usr/src/linux-headers-3.19.0-25-generic/include/config/platform
/usr/src/linux-headers-3.13.0-106-generic/include/config/v4l/platform
/usr/src/linux-headers-3.13.0-106-generic/include/config/x86/platform
/usr/src/linux-headers-3.13.0-106-generic/include/config/wilink/platform
/usr/src/linux-headers-3.13.0-106/include/linux/can/platform
/usr/src/linux-headers-3.13.0-106/include/acpi/platform
/usr/src/linux-headers-3.13.0-106/arch/xtensa/platforms/s6105/include/platform
/usr/src/linux-headers-3.13.0-106/arch/xtensa/platforms/xt2000/include/platform
/usr/src/linux-headers-3.13.0-106/arch/xtensa/platforms/iss/include/platform
/usr/src/linux-headers-3.13.0-106/arch/xtensa/platforms/xtfpga/include/platform
/usr/src/linux-headers-3.13.0-106/arch/x86/platform
/usr/src/linux-headers-3.13.0-106/arch/microblaze/platform
/usr/src/linux-headers-3.13.0-106/arch/m68k/platform
/usr/src/linux-headers-3.13.0-106/drivers/media/platform
/usr/src/linux-headers-3.13.0-106/drivers/platform
/usr/src/linux-headers-3.19.0-25/include/linux/can/platform
/usr/src/linux-headers-3.19.0-25/include/acpi/platform
/usr/src/linux-headers-3.19.0-25/arch/xtensa/platforms/xt2000/include/platform
/usr/src/linux-headers-3.19.0-25/arch/xtensa/platforms/iss/include/platform
/usr/src/linux-headers-3.19.0-25/arch/xtensa/platforms/xtfpga/include/platform
/usr/src/linux-headers-3.19.0-25/arch/x86/platform
/usr/src/linux-headers-3.19.0-25/arch/nios2/platform
/usr/src/linux-headers-3.19.0-25/drivers/media/platform
/usr/src/linux-headers-3.19.0-25/drivers/platform
/usr/lib/jvm/java-8-oracle/lib/visualvm/platform
/usr/share/tcltk/tcl8.6/tcl8/platform
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/stream_executor/platform
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/platform
/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform
/usr/local/cuda-8.0/samples/6_Advanced/interval/boost/config/platform
/usr/include/boost/config/platform```

**Comment by dearhoper** [comment]
I renamed the 'platform' folder to 'platform-' under the /usr/local/lib/python2.7/dist-packages/tensorflow/python. Then the problem was solved.

But, the tensorflow cann't find its own platform .....

Anyway, thank you very much for your help!
