### ISSUE TITLE
Test failures with 2.7 and 3.6

### ISSUE THREAD

**Issue by FRidh** [pydata/numexpr#315]
```
..Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/build/numexpr-2.6.8/numexpr/__init__.py", line 24, in <module>
    from __config__ import show as show_config, get_info
ModuleNotFoundError: No module named '__config__'
E....................Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/build/numexpr-2.6.8/numexpr/__init__.py", line 24, in <module>
    from __config__ import show as show_config, get_info
ModuleNotFoundError: No module named '__config__'
E.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*Warning*: NumPy version is lower than recommended: 1.15.1 < 1.7.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.8
NumPy version:     1.15.1
Python version:    3.6.6 (default, Jun 27 2018, 05:47:41)
[GCC 7.3.0]
Platform:          linux-x86_64-#1-NixOS SMP Sat Aug 18 08:48:00 UTC 2018
CPU vendor:
CPU model:
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 4 (out of 4 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...
======================================================================
ERROR: test_locals_clears_globals (numexpr.tests.test_numexpr.test_numexpr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/numexpr-2.6.8/build/lib.linux-x86_64-3.6/numexpr/tests/test_numexpr.py", line 336, in test_locals_clears_globals
    check = subprocess.check_call('{0} -c "{1}"'.format(sys.executable, script), shell=True)
  File "/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/bin/python3.6m -c "import numexpr as ne;a=10;ne.evaluate('1');a += 1;ne.evaluate('2', local_dict={});a += 1;ne.evaluate('3', global_dict={});a += 1;ne.evaluate('4', local_dict={}, global_dict={});a += 1"' returned non-zero exit status 1.

======================================================================
ERROR: test_locals_clears_globals (numexpr.tests.test_numexpr.test_numexpr2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/numexpr-2.6.8/build/lib.linux-x86_64-3.6/numexpr/tests/test_numexpr.py", line 336, in test_locals_clears_globals
    check = subprocess.check_call('{0} -c "{1}"'.format(sys.executable, script), shell=True)
  File "/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/bin/python3.6m -c "import numexpr as ne;a=10;ne.evaluate('1');a += 1;ne.evaluate('2', local_dict={});a += 1;ne.evaluate('3', global_dict={});a += 1;ne.evaluate('4', local_dict={}, global_dict={});a += 1"' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 5520 tests in 3.998s

FAILED (errors=2)
```

**Comment by FRidh** [comment]
It may be related to how we test. We run the following script:
```py
    import sysconfig
    import sys
    import os
    f = "lib.{platform}-{version[0]}.{version[1]}"
    lib = f.format(platform=sysconfig.get_platform(),
                   version=sys.version_info)
    build = os.path.join(os.getcwd(), 'build', lib)
    sys.path.insert(0, build)
    import numexpr
    r = numexpr.test()
    if not r.wasSuccessful():
        sys.exit(1)
```

**Comment by FRidh** [comment]
The issue was introduced with 2.6.8.

**Comment by robbmcleod** [comment]
So you don't want to install the package beforehand for some reason? In which case the obvious thing to do is modify the shell environment? Because I'd guess your adding to `sys.path` isn't propagating to the subprocess call there. What about setting `os.environ['PYTHONPATH'] = build`?

**Comment by FRidh** [comment]
We don't have a single site-packages folder but one for every individual package. I don't know why the script as above was run or needed, but I solved it now by throwing away the `sys.path` manipulation and moving out of the build dir before running it.
