### ISSUE TITLE
NE3: Pow (**) throws KeyError for long operands

### ISSUE THREAD

**Issue by sg0wtham** [pydata/numexpr#324]
The power (**) operator works well when any one of the operands is float, but when both are int/long the following KeyError occurs.  This problem was not found in numexpr2.

>>numexpr3.evaluate('2**2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gowtham/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numexpr3/ne3compiler.py", line 302, in evaluate
    neObj = NumExpr(expr, lib=lib, casting=casting, stackDepth=stackDepth+1)
  File "/home/gowtham/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numexpr3/ne3compiler.py", line 440, in __init__
    self._assemble()
  File "/home/gowtham/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numexpr3/ne3compiler.py", line 485, in _assemble
    _ASTAssembler[type(bodyItem),-1](self,bodyItem)
  File "/home/gowtham/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numexpr3/ne3compiler.py", line 934, in _expression_last
    valueReg = _ASTAssembler[type(node.value)](self, node.value)
  File "/home/gowtham/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numexpr3/ne3compiler.py", line 1253, in _binop
    raise e
  File "/home/gowtham/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numexpr3/ne3compiler.py", line 1246, in _binop
    opWord, self.assignDChar = OPTABLE[(type(node.op), self.lib, leftRegister.dchar, rightRegister.dchar)]
KeyError: (<class '_ast.Pow'>, 0, 'l', 'l')

**Comment by robbmcleod** [comment]
Should be fixed now in https://github.com/pydata/numexpr/commit/0735b9db8ed18761bfbfd02aa788c90b4271aac9 but I still need to also provide integer implementations for `//` and `mod`.

**Comment by robbmcleod** [comment]
Ok added floordiv and mod for integers in 50898864715992de23ba3ea5798ffa67c3d6ef1b. So this is resolved for now. If you find otherwise, please reopen the issue.
