### ISSUE TITLE
Failing tests with numpy 1.18.0

### ISSUE THREAD

**Issue by FRidh** [pydata/numexpr#354]
- Python 3.7.6
- numpy 1.18.0
- numexpr 2.7.0
```
======================================================================
ERROR: test_changing_nthreads_00_inc (numexpr.tests.test_numexpr.test_evaluate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/9jl7rqxx2x5y8x2nv5h6zi93x6aw97v7-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/wv4mwsc76kq7a21x7fp86k5xw9dayr07-python3.7-numexpr-2.7.0/lib/python3.7/site-packages/numexpr/tests/test_numexpr.py", line 508, in test_changing_nthreads_00_inc
    a = linspace(-1, 1, 1e6)
  File "<__array_function__ internals>", line 6, in linspace
  File "/nix/store/9jl7rqxx2x5y8x2nv5h6zi93x6aw97v7-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

======================================================================
ERROR: test_changing_nthreads_01_dec (numexpr.tests.test_numexpr.test_evaluate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/9jl7rqxx2x5y8x2nv5h6zi93x6aw97v7-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/wv4mwsc76kq7a21x7fp86k5xw9dayr07-python3.7-numexpr-2.7.0/lib/python3.7/site-packages/numexpr/tests/test_numexpr.py", line 516, in test_changing_nthreads_01_dec
    a = linspace(-1, 1, 1e6)
  File "<__array_function__ internals>", line 6, in linspace
  File "/nix/store/9jl7rqxx2x5y8x2nv5h6zi93x6aw97v7-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

----------------------------------------------------------------------
Ran 5522 tests in 4.102s
```

**Comment by robbmcleod** [comment]
At first glance it looks like some `numpy` function is returning `float` when it used to return `int` in 1.18.

**Comment by robbmcleod** [comment]
Should be fixed in https://github.com/pydata/numexpr/commit/3f96a2905af62b7dd840f343977a773df5c74ca7, although Appveyor continues to fail in 3.8 for Windows. I'll look into releasing 2.7.1 today or tomorrow.
