### ISSUE TITLE
The occasional crash occurs when calling MKL functions inside the numexpr module.

### ISSUE THREAD

**Issue by AndrewTsao** [pydata/numexpr#448]
When using pandas, I occasionally encounter the following crash, which has a very low probability of occurrence, about 1/100. Check the core file, the stack information is as follows.

```
#0  0x00002aea291662bd in getenv () from /lib64/libc.so.6
#1  0x00002aea2fd5f149 in mkl_serv_getenv () from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/mkl/../../../libmkl_rt.so.1
#2  0x00002aea3e08a425 in mkl_vml_kernel_ReadEnvVarMode () from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/mkl/../../../libmkl_vml_avx512.so.1
#3  0x00002aea3e08a163 in mkl_vml_kernel_GetMode () from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/mkl/../../../libmkl_vml_avx512.so.1
#4  0x00002aea3e08a136 in mkl_vml_kernel_GetTTableIndex () from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/mkl/../../../libmkl_vml_avx512.so.1
#5  0x00002aea399e8647 in vdDiv () from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/mkl/../../../libmkl_intel_lp64.so.1
#6  0x00002aea3f79c421 in vm_engine_iter_task(NpyIter_InternalOnly*, long*, vm_params const&, int*, char**) [clone .localalias.0] ()
   from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so
#7  0x00002aea3f7c6045 in th_worker(void*) () from /home/and/Anacondas/Anaconda3_2021_11/lib/python3.9/site-packages/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so
#8  0x00002aea28f18ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00002aea2922bb0d in setfsuid () from /lib64/libc.so.6
#10 0x0000000000000000 in ?? ()
```

My python environments:
```
python 3.9
centos 7.9
mkl-fft                            1.3.1
mkl-random                         1.2.2
mkl-service                        2.4.0
numexpr                            2.7.3
pandas                             1.3.4
numpy                              1.20.3
```

**Comment by robbmcleod** [comment]
Honestly, there's probably something corrupted in one of your binaries. In any case, the error originates in MKL. Try making a new environment with up-to-date packages and see if the problem resolves.
